name: Testing | AutoLabel
on: [pull_request, pull_request_review]
jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Review
        uses: Garlic-Team/Auto-Label@main
        with:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REVIEWS: 1
          NEED_REVIEW: "need review"
          APPROVED_REVIEW: "approved"
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
