name: Testing | AutoLabel
on: [pull_request, pull_request_review]
jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Review
        uses: xHyroM/testaction@main
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWS: 2
          NEED_REVIEW: "need review"
          APPROVED_REVIEW: "approved"
